//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MineControl.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string appGPUMinerName {
            get {
                return ((string)(this["appGPUMinerName"]));
            }
            set {
                this["appGPUMinerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string appGPUMinerPath {
            get {
                return ((string)(this["appGPUMinerPath"]));
            }
            set {
                this["appGPUMinerPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string appCPUMinerName {
            get {
                return ((string)(this["appCPUMinerName"]));
            }
            set {
                this["appCPUMinerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string appCPUMinerPath {
            get {
                return ((string)(this["appCPUMinerPath"]));
            }
            set {
                this["appCPUMinerPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string appHardwareMonitorName {
            get {
                return ((string)(this["appHardwareMonitorName"]));
            }
            set {
                this["appHardwareMonitorName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string appHardwareMonitorPath {
            get {
                return ((string)(this["appHardwareMonitorPath"]));
            }
            set {
                this["appHardwareMonitorPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string appGPUControllerName {
            get {
                return ((string)(this["appGPUControllerName"]));
            }
            set {
                this["appGPUControllerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string appGPUControllerPath {
            get {
                return ((string)(this["appGPUControllerPath"]));
            }
            set {
                this["appGPUControllerPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool minerEnableAutomation {
            get {
                return ((bool)(this["minerEnableAutomation"]));
            }
            set {
                this["minerEnableAutomation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int minerGPUMode {
            get {
                return ((int)(this["minerGPUMode"]));
            }
            set {
                this["minerGPUMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int minerCPUMode {
            get {
                return ((int)(this["minerCPUMode"]));
            }
            set {
                this["minerCPUMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tempEnableAutomation {
            get {
                return ((bool)(this["tempEnableAutomation"]));
            }
            set {
                this["tempEnableAutomation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int tempSpeedStep {
            get {
                return ((int)(this["tempSpeedStep"]));
            }
            set {
                this["tempSpeedStep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-profile1")]
        public string tempPowerStepParam1 {
            get {
                return ((string)(this["tempPowerStepParam1"]));
            }
            set {
                this["tempPowerStepParam1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-profile2")]
        public string tempPowerStepParam2 {
            get {
                return ((string)(this["tempPowerStepParam2"]));
            }
            set {
                this["tempPowerStepParam2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-profile3")]
        public string tempPowerStepParam3 {
            get {
                return ((string)(this["tempPowerStepParam3"]));
            }
            set {
                this["tempPowerStepParam3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-profile4")]
        public string tempPowerStepParam4 {
            get {
                return ((string)(this["tempPowerStepParam4"]));
            }
            set {
                this["tempPowerStepParam4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-profile5")]
        public string tempPowerStepParam5 {
            get {
                return ((string)(this["tempPowerStepParam5"]));
            }
            set {
                this["tempPowerStepParam5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int tempStopWhenOverheatSecs {
            get {
                return ((int)(this["tempStopWhenOverheatSecs"]));
            }
            set {
                this["tempStopWhenOverheatSecs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int tempStopWhenOverheatThresholdSecs {
            get {
                return ((int)(this["tempStopWhenOverheatThresholdSecs"]));
            }
            set {
                this["tempStopWhenOverheatThresholdSecs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("86")]
        public int tempMin {
            get {
                return ((int)(this["tempMin"]));
            }
            set {
                this["tempMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("92")]
        public int tempMax {
            get {
                return ((int)(this["tempMax"]));
            }
            set {
                this["tempMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int tempPollingIntervalMillisecs {
            get {
                return ((int)(this["tempPollingIntervalMillisecs"]));
            }
            set {
                this["tempPollingIntervalMillisecs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool controlStartupMinimize {
            get {
                return ((bool)(this["controlStartupMinimize"]));
            }
            set {
                this["controlStartupMinimize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool controlStartupRememberAutomation {
            get {
                return ((bool)(this["controlStartupRememberAutomation"]));
            }
            set {
                this["controlStartupRememberAutomation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool controlRunning {
            get {
                return ((bool)(this["controlRunning"]));
            }
            set {
                this["controlRunning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int tempSpeedStepBuffer {
            get {
                return ((int)(this["tempSpeedStepBuffer"]));
            }
            set {
                this["tempSpeedStepBuffer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool controlMinimizeToSysTray {
            get {
                return ((bool)(this["controlMinimizeToSysTray"]));
            }
            set {
                this["controlMinimizeToSysTray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int tempTryStepUpSecs {
            get {
                return ((int)(this["tempTryStepUpSecs"]));
            }
            set {
                this["tempTryStepUpSecs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool tempTryStepUp {
            get {
                return ((bool)(this["tempTryStepUp"]));
            }
            set {
                this["tempTryStepUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int generalSysTrayDisplayMode {
            get {
                return ((int)(this["generalSysTrayDisplayMode"]));
            }
            set {
                this["generalSysTrayDisplayMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool chartMinTempOnYAxisEnabled {
            get {
                return ((bool)(this["chartMinTempOnYAxisEnabled"]));
            }
            set {
                this["chartMinTempOnYAxisEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int chartMinTempOnYAxisValue {
            get {
                return ((int)(this["chartMinTempOnYAxisValue"]));
            }
            set {
                this["chartMinTempOnYAxisValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string scheduleSerializedSchedules {
            get {
                return ((string)(this["scheduleSerializedSchedules"]));
            }
            set {
                this["scheduleSerializedSchedules"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000-0000-0000-0000-000000000000")]
        public global::System.Guid minerGPUSchedule {
            get {
                return ((global::System.Guid)(this["minerGPUSchedule"]));
            }
            set {
                this["minerGPUSchedule"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000-0000-0000-0000-000000000000")]
        public global::System.Guid minerCPUSchedule {
            get {
                return ((global::System.Guid)(this["minerCPUSchedule"]));
            }
            set {
                this["minerCPUSchedule"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool minerGPUUserActivityShutoff {
            get {
                return ((bool)(this["minerGPUUserActivityShutoff"]));
            }
            set {
                this["minerGPUUserActivityShutoff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool minerCPUUserActivityShutoff {
            get {
                return ((bool)(this["minerCPUUserActivityShutoff"]));
            }
            set {
                this["minerCPUUserActivityShutoff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool tempStopWhenTempUnknown {
            get {
                return ((bool)(this["tempStopWhenTempUnknown"]));
            }
            set {
                this["tempStopWhenTempUnknown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool tempStopWhenOverheat {
            get {
                return ((bool)(this["tempStopWhenOverheat"]));
            }
            set {
                this["tempStopWhenOverheat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int minerUserActivityTimeoutMins {
            get {
                return ((int)(this["minerUserActivityTimeoutMins"]));
            }
            set {
                this["minerUserActivityTimeoutMins"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool minerGPUShowLogs {
            get {
                return ((bool)(this["minerGPUShowLogs"]));
            }
            set {
                this["minerGPUShowLogs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool minerCPUShowLogs {
            get {
                return ((bool)(this["minerCPUShowLogs"]));
            }
            set {
                this["minerCPUShowLogs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool archivesArchiveConfig {
            get {
                return ((bool)(this["archivesArchiveConfig"]));
            }
            set {
                this["archivesArchiveConfig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int archivesArchiveInterval {
            get {
                return ((int)(this["archivesArchiveInterval"]));
            }
            set {
                this["archivesArchiveInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string archivesArchiveIntervalUnit {
            get {
                return ((string)(this["archivesArchiveIntervalUnit"]));
            }
            set {
                this["archivesArchiveIntervalUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool archivesLogManagement {
            get {
                return ((bool)(this["archivesLogManagement"]));
            }
            set {
                this["archivesLogManagement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string archivesLogManagementType {
            get {
                return ((string)(this["archivesLogManagementType"]));
            }
            set {
                this["archivesLogManagementType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int archivesLogManagementValue {
            get {
                return ((int)(this["archivesLogManagementValue"]));
            }
            set {
                this["archivesLogManagementValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string archivesLogManagementUnit {
            get {
                return ((string)(this["archivesLogManagementUnit"]));
            }
            set {
                this["archivesLogManagementUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string archivesArchiveFolder {
            get {
                return ((string)(this["archivesArchiveFolder"]));
            }
            set {
                this["archivesArchiveFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool archivesDeleteOldFiles {
            get {
                return ((bool)(this["archivesDeleteOldFiles"]));
            }
            set {
                this["archivesDeleteOldFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int archivesDeleteOldFilesDays {
            get {
                return ((int)(this["archivesDeleteOldFilesDays"]));
            }
            set {
                this["archivesDeleteOldFilesDays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string metricsSerializedMetrics {
            get {
                return ((string)(this["metricsSerializedMetrics"]));
            }
            set {
                this["metricsSerializedMetrics"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string metricsSerializedMetricQueryOptions {
            get {
                return ((string)(this["metricsSerializedMetricQueryOptions"]));
            }
            set {
                this["metricsSerializedMetricQueryOptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool archivesClearOldCharts {
            get {
                return ((bool)(this["archivesClearOldCharts"]));
            }
            set {
                this["archivesClearOldCharts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int archivesClearOldChartsValue {
            get {
                return ((int)(this["archivesClearOldChartsValue"]));
            }
            set {
                this["archivesClearOldChartsValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Days")]
        public string archivesClearOldChartsUnit {
            get {
                return ((string)(this["archivesClearOldChartsUnit"]));
            }
            set {
                this["archivesClearOldChartsUnit"] = value;
            }
        }
    }
}
